### ISSUE TITLE
how to load self jieba

### ISSUE THREAD

**Issue by policeme** [chakki-works/sumeval#14]

**Comment by policeme** [comment]
I want to load self jieba, because the original jieba has very different stop word with my vocab

**Comment by icoxfog417** [comment]
Do you mean you want to use a custom stop word list? Now sumeval does not support it but you could set your stop word list by the following code.

```py
rouge = RougeCalculator(stopwords=True, lang="zh")
rouge.lang._stopwords = your_stop_word_list
```

**Comment by policeme** [comment]
but my jieba has different vocabs and stop vocobs,  if you can support load custom jieba when init jieba, it very excellent.

**Comment by icoxfog417** [comment]
Now you can use custom lang to use your own parser.

https://github.com/chakki-works/sumeval/blob/master/tests/test_custom_lang.py#L11
