### ISSUE TITLE
Are the references single sentences or summaries with many sentences?

### ISSUE THREAD

**Issue by radkoff** [chakki-works/sumeval#15]
Hi, the docs aren't quite clear: lets say I have two different gold standard annotations, each of which includes 2 sentences chosen as good summary sentences. Do I pass them both into the ROUGE methods like this?
```
rouge.rouge_2(summary, [
   'Sentence one from annotation one. Sentence two from annotation one.',
   'Sentence one from annotation two. Sentence two from annotation two.'
])
```
Or do I call rouge_2 multiple times, once for each gold standard annotation, and average the results?
```
rouge.rouge_2(summary, ['Sentence one from annotation one.', 'Sentence two from annotation one.'])
rouge.rouge_2(summary, ['Sentence one from annotation two.', 'Sentence two from annotation two.'])
```

**Comment by icoxfog417** [comment]
Yes, you can do both. Please refer How to use.

https://github.com/chakki-works/sumeval#how-to-use
