### ISSUE TITLE
What exactly does rouge_be measure?

### ISSUE THREAD

**Issue by A-Gulati** [chakki-works/sumeval#16]
Tried looking through the code but I'm still not exactly clear on what rouge_be is measuring. What is rouge_be measuring?

**Comment by icoxfog417** [comment]
ROUGE BE is described at [Automated Summarization Evaluation with Basic Elements](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/07/lrec_2006_be.pdf), Roughly speaking, this score calculates the match of triple extracted from the dependency tree.
