### ISSUE TITLE
Ginza v2.0への対応

### ISSUE THREAD

**Issue by s-sugawara-chowagiken** [chakki-works/sumeval#17]
Ginza v2.0で言語モデル名が`ja_ginza_nopn`から`ja_ginza`へと変更となったため、Ginza v2.0がインストールされた環境だとROUGE-BE（日本語）で評価しようとすると、lang_ja.pyの[load_parser()](https://github.com/chakki-works/sumeval/blob/master/sumeval/metrics/lang/lang_ja.py#L15)でエラーになります。

Ginza v2.0に対応する予定はありますでしょうか。

**Comment by icoxfog417** [comment]
Thank you for reporting. It'll ve resolved in 0.2.1.
