### ISSUE TITLE
super() takes at least 1 argument(0 given)

### ISSUE THREAD

**Issue by chnherb** [chakki-works/sumeval#3]
in the file:\metrics\lang\lang_en.py, line 8, in __init__ super().__init__("en")
TypeError: super() takes at least 1 argument(0 given)
it causes demo cannot run, please you to correct this mistake
![image](https://user-images.githubusercontent.com/23290487/34946161-b9c15cf4-fa40-11e7-9a36-f5cfe28d3aef.png)

**Comment by icoxfog417** [comment]
Thank you for your reporting!

Do you use Python2? The sumeval mainly supports Python3. So If you could, please try under Python3.
(But I fixed `super` statement for Python2).
