### ISSUE TITLE
Supporting multiple sentences for the calculation of ROUGE-L?

### ISSUE THREAD

**Issue by yuhaozhang** [chakki-works/sumeval#6]
It seems a common practice to calculate ROUGE-L score with multiple sentences instead of stacking all sentences into a single string. Splitting a summary/reference into multiple sentences can impact the way the longest matching sequences are determined, and therefore impact the ROUGE-L score. Does semeval support this?
Note that this is different from having multiple references for each summary. Thanks!

**Comment by icoxfog417** [comment]
Currently sumeval does not support that calculation. Could you show me any paper or implementation about the calculation of ROUGE-L that you mentioned? I want to consider it.

**Comment by yuhaozhang** [comment]
Section 3.2 of [the original ROUGE paper](http://www.aclweb.org/anthology/W04-1013) illustrates how to calculate ROUGE-L when there are multiple sentences in the reference and the summary. The original perl implementation also supports this when I used it (just need to provide each sentence of the reference/summary in different html tags).

**Comment by icoxfog417** [comment]
Thank you for the information! I confirmed the paper and the code.

The perl script seems to only support sentence level ROUGE-L.

* There is no option to calculate summary-level ROUGE-L.
  * [only average or better option](https://github.com/summanlp/evaluation/blob/master/ROUGE-RELEASE-1.5.5/ROUGE-1.5.5.pl#L1427)
* In the model path (each summary sentence) loop, matched part is not merged (only matched count is merged).

[And the comment on the source code suggests the abolition of summary lebel ROUGE-L](https://github.com/summanlp/evaluation/blob/master/ROUGE-RELEASE-1.5.5/ROUGE-1.5.5.pl#L1422). It is deprecated at [1.4.1](https://github.com/summanlp/evaluation/blob/master/ROUGE-RELEASE-1.5.5/ROUGE-1.5.5.pl#L90).
